global:
  fpm:
    image:
      repository: vuongxuongminh/docker-helm-laravel
      tag: production
      pullPolicy: IfNotPresent
    env: 'production'
    debug: 'false'
    url: 'http://example'
    key: '!ChangeMe!'

nginx:
  replicaCount: 1
  existingServerBlockConfigmap: nginx-server-block
  extraVolumes: 
    - name: public-dir
      emptyDir: {}
  extraVolumeMounts:
    - name: public-dir
      mountPath: /laravel/public
  sidecars:
    - name: fpm
      image: '{{ .Values.global.fpm.image.repository }}:{{ .Values.global.fpm.image.tag }}'
      imagePullPolicy: '{{ .Values.global.fpm.image.pullPolicy }}'
      livenessProbe:
        exec:
          command:
            - docker-healthcheck
        initialDelaySeconds: 10
        periodSeconds: 5
      readinessProbe:
        exec:
          command:
            - docker-healthcheck
        initialDelaySeconds: 10
        timeoutSeconds: 5
      envFrom:
        - configMapRef:
            name: '{{ template "fpm" . }}'
        - secretRef:
            name: '{{ template "fpm" . }}'
      ports:
        - name: fpm
          containerPort: 9000