apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fpm" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.global.fpm.key }}
  APP_KEY: {{ .Values.global.fpm.key | b64enc | quote }}
  {{- end }}